### ISSUE TITLE
Correção

### ISSUE THREAD

**Issue by Bernardopog** [FelipeJSantos-Programmer/qr-code-component#1]
Olá Felipe, sou o Bernardo do Frontend Mentor, e aqui está a correção do seu projeto.

[Código](https://github.com/R3ygoski/felipejsantos-qr-code) - Para ver as alterações feitas.
[Site](https://r3ygoski.github.io/felipejsantos-qr-code/) - Para ver o resultado.

Eu removi alguns arquivos como o responsivo, pois ele não era necessário. Também coloquei alguns comentários com link explicando algumas partes, todos esses comentários com links estão escritos no style.css e começam com "**/*?**", para facilitar de encontrar, e se você utilizar o VSCode, basta segurar CTRL ou CMD e clicar sobre o link, que abrirá uma página explicando sobre.

E eu notei que você teve uma dificuldade com a estrutura do HTML, então fiz essa "ilustração", espero que ela ajude a entender como eu pensei em montar a estrutura do HTML.

![image](https://github.com/user-attachments/assets/81b331e3-9483-42d8-944f-d8cad5e2b813)

Caso tenha ficado qualquer dúvida quanto ao código, ou qualquer outra coisa, pode perguntar por aqui, pelo Linkedin (Você encontra no meu perfil) ou até pelo Frontend Mentor, tentarei responder assim que possível.

**Comment by FelipeJSantos-Programmer** [comment]
Opa Bernardo! Acabei de ver suas correções e eu estou surpreso do quão simplificado ficou esse html. Eu não sabia que ao invés de utilizar "**div**" eu poderia substituir apenas pela estrutura do projeto e aplicar as classes dentro dela. Isso é o que chamam de semântica então?

Achei interessante também o fato de não precisar do "responsivo", achava que era algo obrigatório para todos os projetos frontend. Nesse caso, quando eu devo utilizar o "responsivo" dentro do meu projeto?

Vou assistir os links indicados nas suas anotações para compreender as variáveis. Obrigado mais uma vez!

**Comment by Bernardopog** [comment]
Olá novamente Felipe. Exatamente, isso que é a semântica, você evita de utilizar várias `<div>` e utiliza tags mais propícias para aquela situação, como `<header>`, `<nav>`, `<section>` e várias outras tags semânticas. E isso de usar tags semânticas tem outros benefícios, como melhorar o SEO, organizar a estrutura do HTML, aumentar o nível de Acessibilidade.

Sobre a questão do responsivo, você apenas precisa utilizá-lo quando quer fazer várias alterações de uma tela para outra. No caso desse projeto, como era um simples card, poderia ter feito utilizando o `clamp()` que serve para estabelecer um valor mínimo, base e máximo. Mas em projetos de páginas inteiras, seria mais interessante utilizar a responsividade através do `@media`, que serve para criar diferentes estilos para diferentes tamanhos de telas.

E é isso, novamente, não há de que, qualquer futura dúvida que surgir, sinta-se convidado a entrar em contato.
